### ISSUE TITLE
Allergy Mode is missing

### ISSUE THREAD

**Issue by eljarno** [iobroker-community-adapters/ioBroker.philips-air#144]
Right now I cannot change the Allergy Night Mode. When I change it within the App the mode is set to "AS" within the iobroker objects. But when I try to change it via javascript to "AS" nothing happens. I guess the mode can be read but node be changed.

It would be great if you change the Adapter and add the missing mode.

Regards
Jan

**Comment by Apollon77** [comment]
Please provide a log - is it set in the objects to "AS" as string or is it shown as a selection there? Can you set in the onbkjects directly but just not via Javascript? Please provide an info

**Comment by Ralf31337** [comment]
I have exactly the same issue. Can't set it via Objects in IOBroker, because "AS" is not available as a valid value in the drop-down.

In the first two rows, you see the values that come from the device if I set it to allergy sleep via Philips app:
![grafik](https://github.com/user-attachments/assets/6d6af448-00b6-4953-a397-e84848dc9ee1)

If I send the string "AS" it does not work. For "turbo" and "automode" it does work.

**Comment by mcm1957** [comment]
This issue does not contain version infos and log

Please add version infos
adapter
js-controller
admin
node 
o/s

and attach a complete log with loglevel set to DEBUG showing the actions araound setting state 'mode'.

**Comment by Ralf31337** [comment]
Adapter version: v1.1.0
Controller version: v6.17.14

That's the WARN I get, when setting it to "AS" via node-red:
  | warn | Could  not control mode: Invalid option for mode: AS. Supported only:  {"P":"auto","A":"allergen","S":"sleep","M":"manual","B":"bacteria","N":"night","T":"turbo","AG":"automode","GT":"gentle"}

That's what I receive in DEBUG, when setting to Allergy Sleep in the app:
State  change:  {"val":"AS","ack":true,"ts":1733162331433,"q":0,"from":"system.adapter.philips-air.0","user":"system.user.admin","lc":1733162255368}

I think it is not allowed from what I can see in the code:
https://github.com/iobroker-community-adapters/ioBroker.philips-air/blob/fc2e700d9cd4b5fd2ae17245c3aed6df3862cd4d/lib/coap.js#L34

There is an allergen available, but the AC4236 has a different name for it. Does it make sense to add all variants? Or make the adapter device specific? Philips seems to be really inconsistent here. :-(

**Comment by mcm1957** [comment]
Yes - I already considered to ask wether this functionality ever worked as I did not see an AS entry too.

As you already detected this code, I would suggest that you - AS AN EXCEPTION FOR FIXING - and if you are a little bit familar with some editor try to change the code an insert some 'AS': 'allergen' or 'AS': 'allergen2' entry. I do not have the equipment to test anything and mosg likely I do not have time to provide test releases but I can offer to create a new release if at least a testable fix is available.

Of course an PR would be welcom most if you are familar with GitHub.

**Comment by Ralf31337** [comment]
I will create a PR and do the modifications.

**Comment by mcm1957** [comment]
@Ralf31337 Dis you ever create a PR? I did not find a note at Releanotes and no matching PR.
I just want to make sure that no work got lost.

**Comment by mcm1957** [comment]
Thanjs for feedback. I just wanted to ensure that nothing got list.

**Comment by eljarno** [comment]
I'm still using the adapter but it's still missing. When I manually set my filter to Allergy Mode, the property Mode contains the string "AS". But I'm not able to set this mode via the adapter by choosing one of the given options.

**Comment by mcm1957** [comment]
> I'm still using the adapter but it's still missing. When I manually set my filter to Allergy Mode, the property Mode contains the string "AS". But I'm not able to set this mode via the adapter by choosing one of the given options.

Not really a news as this issue is still open. Did you read prev. comments (https://github.com/iobroker-community-adapters/ioBroker.philips-air/issues/144#issuecomment-2648928465) ?

**Comment by mcm1957** [comment]
> Yes but after I published my comment. Sorry for that

No real problem. I was a little bit stressed so I answered not very friendly. I too hope, that A PR will arrive - dont have time and tsting possibility to do anything myself

**Comment by tt-tom17** [comment]
@eljarno 
Is this still an issue? Please try version 2.0.0

**Comment by tt-tom17** [comment]
no response, closed.
